# Generated by Django 5.0.6 on 2024-11-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentiment_analysis", "0002_alter_sentiment_results_news_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news_details",
            name="news_category",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="news_details",
            name="news_topic",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sentiment_results",
            name="news_category",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sentiment_results",
            name="news_link",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="sentiment_results",
            name="news_topic",
            field=models.CharField(default="", max_length=255),
        ),
    ]
